[workspace]
members = [".", "./derive_pod"]

[package]
name = "dataview"
version = "1.1.0"
edition = "2024"
rust-version = "1.85"

license = "MIT"
authors = ["Casper <CasualX@users.noreply.github.com>"]
description = "Safe transmute between types and byte arrays of the same size."
documentation = "https://docs.rs/dataview/"
repository = "https://github.com/CasualX/dataview"
readme = "readme.md"
keywords = ["binary", "data", "view", "pod"]
categories = ["parser-implementations"]

[package.metadata.docs.rs]
features = ["derive_pod"]

[features]
default = ["derive_pod"]

[dependencies]
derive_pod = { path = "./derive_pod", version = "0.1.3", optional = true }
