name: Gate

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: Test (nightly)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v7

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly

      - name: Run tests
        run: cargo test
