name: Gate

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: Test (${{ matrix.rust }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [1.85, stable, beta, nightly]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v7

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}

      - name: Run tests
        run: cargo test
